"""
Alert Model

Security alerts generated by detection rules, YARA matches,
behavioral analysis, or LLM-powered threat analysis.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, DateTime, Integer, Text, Float, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class Alert(Base):
    """Security alert generated from telemetry analysis."""

    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # --- Source ---
    agent_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("agents.id"), nullable=False, index=True
    )

    # --- Classification ---
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False, index=True
    )  # critical | high | medium | low | informational
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)  # 0.0 - 1.0
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="new", index=True
    )  # new | investigating | resolved | false_positive | escalated

    # --- Detection Source ---
    detection_source: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # yara | sigma | behavioral | llm | correlation | manual
    rule_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    rule_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # --- MITRE ATT&CK Mapping ---
    mitre_tactics: Mapped[list | None] = mapped_column(ARRAY(String), nullable=True)
    mitre_techniques: Mapped[list | None] = mapped_column(ARRAY(String), nullable=True)

    # --- Enrichment ---
    related_cves: Mapped[list | None] = mapped_column(ARRAY(String), nullable=True)
    ioc_indicators: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # --- LLM Analysis ---
    llm_analysis: Mapped[str | None] = mapped_column(Text, nullable=True)
    llm_recommendation: Mapped[str | None] = mapped_column(Text, nullable=True)
    llm_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)

    # --- Evidence ---
    raw_events: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    process_tree: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    network_context: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # --- Response ---
    response_actions: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # Actions taken
    assigned_to: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )

    # --- Correlation ---
    correlation_group: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    related_alert_count: Mapped[int] = mapped_column(Integer, default=0)

    # --- Timestamps ---
    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    first_event_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_event_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    def __repr__(self) -> str:
        return (
            f"<Alert(id={self.id}, title={self.title[:50]}, "
            f"severity={self.severity}, status={self.status})>"
        )
