//! SentinelAI Agent v2 — Local Detection Module
//!
//! On-agent detection engine that evaluates telemetry events against
//! signature rules, YARA patterns, and heuristics before they leave
//! the endpoint.
//!
//! # Why Local Detection?
//!
//! 1. **Latency**: Critical detections (Mimikatz, ransomware) trigger
//!    local response actions within milliseconds, not seconds.
//! 2. **Resilience**: Detection continues even if backend is unreachable.
//! 3. **Bandwidth**: Only high-confidence alerts need enrichment server-side.
//! 4. **Defense-in-depth**: Even if network detection is bypassed, local
//!    detection provides a second chance.
//!
//! # Architecture
//!
//! ```text
//! NormalizedEvent (from pipeline)
//!      │
//!      ▼
//! ┌──────────────────────────────────────────────────────┐
//! │              Local Detection Engine                    │
//! │                                                        │
//! │  ┌──────────────┐  ┌────────────┐  ┌──────────────┐  │
//! │  │ Sigma Rules   │  │ YARA Rules  │  │ Heuristics   │  │
//! │  │ (500+ rules)  │  │ (file scan) │  │ (built-in)   │  │
//! │  └──────┬───────┘  └──────┬─────┘  └──────┬───────┘  │
//! │         │                 │                │          │
//! │         └────────┬────────┘────────────────┘          │
//! │                  │                                     │
//! │                  ▼                                     │
//! │         ┌─────────────────┐                            │
//! │         │  Alert Manager   │                            │
//! │         │  (dedup, queue)  │                            │
//! │         └────────┬────────┘                            │
//! │                  │                                     │
//! │                  ▼                                     │
//! │  ┌─────────────────────────────────────┐              │
//! │  │  risk_score + mitre_techniques       │              │
//! │  │  written back to NormalizedEvent     │              │
//! │  │  + LocalAlert sent to transport      │              │
//! │  └─────────────────────────────────────┘              │
//! └──────────────────────────────────────────────────────┘
//! ```

use std::collections::HashMap;
use crate::collector::EventCategory;
use crate::event_pipeline::NormalizedEvent;

// ─── Detection Rule Types ───────────────────────────────────────

/// A compiled Sigma rule ready for evaluation.
#[derive(Debug, Clone)]
pub struct CompiledSigmaRule {
    pub id: String,
    pub name: String,
    pub severity: Severity,
    pub mitre_techniques: Vec<String>,
    /// Pre-compiled filter expression tree.
    pub filter: FilterExpression,
    /// Event categories this rule applies to (skip evaluation for others).
    pub applicable_categories: Vec<EventCategory>,
}

/// Filter expression tree for efficient rule evaluation.
#[derive(Debug, Clone)]
pub enum FilterExpression {
    /// Field equals value (case-insensitive).
    FieldEquals { field: String, value: String },
    /// Field contains substring (case-insensitive).
    FieldContains { field: String, substring: String },
    /// Field matches regex pattern (pre-compiled).
    FieldRegex { field: String, pattern: String },
    /// Field starts with prefix.
    FieldStartsWith { field: String, prefix: String },
    /// Field ends with suffix.
    FieldEndsWith { field: String, suffix: String },
    /// Field exists and is non-empty.
    FieldExists { field: String },
    /// Field is in a set of values.
    FieldIn { field: String, values: Vec<String> },
    /// Logical AND of sub-expressions.
    And(Vec<FilterExpression>),
    /// Logical OR of sub-expressions.
    Or(Vec<FilterExpression>),
    /// Logical NOT of a sub-expression.
    Not(Box<FilterExpression>),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    Info = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4,
}

/// Result of evaluating a single rule against an event.
#[derive(Debug, Clone)]
pub struct RuleMatch {
    pub rule_id: String,
    pub rule_name: String,
    pub severity: Severity,
    pub mitre_techniques: Vec<String>,
    pub confidence: f32, // 0.0 - 1.0
    pub context: HashMap<String, String>,
}

/// Local alert generated by the detection engine.
#[derive(Debug, Clone)]
pub struct LocalAlert {
    pub alert_id: String,
    pub rule_matches: Vec<RuleMatch>,
    pub risk_score: u32,
    pub triggering_event: NormalizedEvent,
    pub recommended_action: ResponseAction,
    pub detected_at_ns: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResponseAction {
    LogOnly,
    Alert,
    IsolateProcess,
    IsolateHost,
    CollectArtifact,
    KillProcess,
}

// ─── Detection Engine ───────────────────────────────────────────

/// The local detection engine that evaluates events against rules.
///
/// # Thread Safety
///
/// The engine is designed to be called from the event pipeline task.
/// Rule loading is done via interior mutability (RwLock on rules vec).
///
/// # Performance Target
///
/// - 500 Sigma rules evaluated in < 500μs per event
/// - YARA scan in < 10ms per file (only for file events with content)
/// - Total detection overhead: < 1ms per event (excluding YARA)
pub struct DetectionEngine {
    /// Compiled Sigma rules.
    sigma_rules: Vec<CompiledSigmaRule>,
    /// Built-in heuristic rules (hardcoded, always active).
    heuristic_rules: Vec<HeuristicRule>,
    /// YARA rule set (compiled, for file scanning).
    yara_rules: Option<YaraRuleSet>,
    /// IOC bloom filter for fast hash/domain/IP matching.
    ioc_filter: IocBloomFilter,
    /// Alert deduplication state.
    alert_dedup: AlertDedup,
    /// Metrics.
    metrics: DetectionMetrics,
}

/// A built-in heuristic rule (not loadable from YAML).
#[derive(Debug, Clone)]
pub struct HeuristicRule {
    pub id: String,
    pub name: String,
    pub severity: Severity,
    pub mitre_techniques: Vec<String>,
    /// Evaluation function (compiled into the binary).
    pub evaluator: fn(&NormalizedEvent, &HashMap<String, String>) -> bool,
}

/// Wrapper for compiled YARA rules.
pub struct YaraRuleSet {
    // In production: yara::Rules from the yara-rust crate
    _placeholder: (),
}

impl std::fmt::Debug for YaraRuleSet {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "YaraRuleSet")
    }
}

/// Bloom filter for fast IOC matching.
///
/// Uses a two-level approach:
/// 1. Bloom filter for O(1) negative lookup (99.9% of events)
/// 2. HashSet for confirmation on positive bloom hits
pub struct IocBloomFilter {
    // In production: probabilistic::BloomFilter + HashSet<String>
    pub bad_hashes: std::collections::HashSet<String>,
    pub bad_domains: std::collections::HashSet<String>,
    pub bad_ips: std::collections::HashSet<String>,
}

impl std::fmt::Debug for IocBloomFilter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "IocBloomFilter(hashes={}, domains={}, ips={})",
            self.bad_hashes.len(),
            self.bad_domains.len(),
            self.bad_ips.len()
        )
    }
}

/// Alert deduplication to avoid flooding the backend with identical alerts.
///
/// Uses a time-windowed seen set:
/// - Same (rule_id, key_fields_hash) within 60s → suppress
/// - After 60s → allow again
pub struct AlertDedup {
    // In production: LRU cache with TTL
    _placeholder: (),
}

impl std::fmt::Debug for AlertDedup {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "AlertDedup")
    }
}

/// Detection engine metrics.
#[derive(Debug, Clone, Default)]
pub struct DetectionMetrics {
    pub events_evaluated: u64,
    pub sigma_matches: u64,
    pub yara_matches: u64,
    pub heuristic_matches: u64,
    pub ioc_matches: u64,
    pub alerts_generated: u64,
    pub alerts_deduplicated: u64,
    pub avg_evaluation_us: u64,
    pub rules_loaded: u32,
}

impl DetectionEngine {
    /// Create a new detection engine with built-in heuristic rules.
    pub fn new() -> Self {
        Self {
            sigma_rules: Vec::new(),
            heuristic_rules: builtin_heuristics(),
            yara_rules: None,
            ioc_filter: IocBloomFilter {
                bad_hashes: std::collections::HashSet::new(),
                bad_domains: std::collections::HashSet::new(),
                bad_ips: std::collections::HashSet::new(),
            },
            alert_dedup: AlertDedup { _placeholder: () },
            metrics: DetectionMetrics::default(),
        }
    }

    /// Evaluate an event against all rules.
    ///
    /// Returns:
    /// - `risk_score` (0-100) to stamp on the event
    /// - `mitre_techniques` to tag the event
    /// - Optional `LocalAlert` if any high-confidence rules matched
    pub fn evaluate(
        &mut self,
        event: &NormalizedEvent,
    ) -> (u32, Vec<String>, Option<LocalAlert>) {
        let mut matches = Vec::new();
        let mut risk_score: u32 = 0;
        let mut techniques = Vec::new();

        // 1. Sigma rules (fast path)
        for rule in &self.sigma_rules {
            if !rule.applicable_categories.contains(&event.category) {
                continue;
            }
            // TODO: evaluate filter expression against event fields
            // Placeholder: matches would be populated here
        }

        // 2. IOC matching (bloom filter + confirmation)
        // TODO: extract hashes/domains/IPs from event and check bloom filter

        // 3. Heuristic rules
        let fields = HashMap::new(); // TODO: extract from event payload
        for rule in &self.heuristic_rules {
            if (rule.evaluator)(event, &fields) {
                matches.push(RuleMatch {
                    rule_id: rule.id.clone(),
                    rule_name: rule.name.clone(),
                    severity: rule.severity,
                    mitre_techniques: rule.mitre_techniques.clone(),
                    confidence: 0.9,
                    context: HashMap::new(),
                });
            }
        }

        // 4. Aggregate risk score
        for m in &matches {
            let severity_score = match m.severity {
                Severity::Info => 5,
                Severity::Low => 15,
                Severity::Medium => 35,
                Severity::High => 65,
                Severity::Critical => 90,
            };
            risk_score = risk_score.max(severity_score);
            techniques.extend(m.mitre_techniques.clone());
        }
        techniques.sort();
        techniques.dedup();

        // 5. Generate alert if risk is significant
        let alert = if risk_score >= 35 {
            let action = if risk_score >= 90 {
                ResponseAction::IsolateProcess
            } else if risk_score >= 65 {
                ResponseAction::Alert
            } else {
                ResponseAction::LogOnly
            };

            Some(LocalAlert {
                alert_id: uuid::Uuid::new_v4().to_string(),
                rule_matches: matches,
                risk_score,
                triggering_event: event.clone(),
                recommended_action: action,
                detected_at_ns: std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_nanos() as u64,
            })
        } else {
            None
        };

        self.metrics.events_evaluated += 1;
        if alert.is_some() {
            self.metrics.alerts_generated += 1;
        }

        (risk_score, techniques, alert)
    }

    /// Load Sigma rules from YAML bytes.
    pub fn load_sigma_rules(&mut self, _rules_yaml: &[u8]) -> Result<usize, String> {
        // TODO: Parse Sigma YAML, compile to FilterExpression trees
        // Return number of rules loaded
        Ok(0)
    }

    /// Load YARA rules from a compiled rule file.
    pub fn load_yara_rules(&mut self, _rules_bytes: &[u8]) -> Result<(), String> {
        // TODO: Use yara-rust to load compiled rules
        Ok(())
    }

    /// Update IOC lists (hashes, domains, IPs).
    pub fn update_iocs(
        &mut self,
        hashes: Vec<String>,
        domains: Vec<String>,
        ips: Vec<String>,
    ) {
        self.ioc_filter.bad_hashes = hashes.into_iter().collect();
        self.ioc_filter.bad_domains = domains.into_iter().collect();
        self.ioc_filter.bad_ips = ips.into_iter().collect();
    }

    /// Get detection engine metrics.
    pub fn metrics(&self) -> &DetectionMetrics {
        &self.metrics
    }
}

// ─── Built-in Heuristics ────────────────────────────────────────

fn builtin_heuristics() -> Vec<HeuristicRule> {
    vec![
        HeuristicRule {
            id: "HEUR-001".into(),
            name: "Mimikatz Process Name".into(),
            severity: Severity::Critical,
            mitre_techniques: vec!["T1003.001".into()],
            evaluator: |event, _fields| {
                // Check if process name contains "mimikatz"
                event.action == "create"
                    && event.category == EventCategory::Process
                    // Real implementation would check payload_bytes
            },
        },
        HeuristicRule {
            id: "HEUR-002".into(),
            name: "Encoded PowerShell Command".into(),
            severity: Severity::High,
            mitre_techniques: vec!["T1059.001".into()],
            evaluator: |event, _fields| {
                event.action == "create"
                    && event.category == EventCategory::Process
                    // Real implementation: check command_line for -enc/-encodedcommand
            },
        },
        HeuristicRule {
            id: "HEUR-003".into(),
            name: "Shadow Copy Deletion".into(),
            severity: Severity::Critical,
            mitre_techniques: vec!["T1490".into()],
            evaluator: |event, _fields| {
                event.action == "create"
                    && event.category == EventCategory::Process
                    // Real implementation: check command_line for "delete shadows"
            },
        },
        HeuristicRule {
            id: "HEUR-004".into(),
            name: "LSASS Memory Access".into(),
            severity: Severity::Critical,
            mitre_techniques: vec!["T1003.001".into()],
            evaluator: |event, _fields| {
                event.category == EventCategory::Process
                    // Real implementation: detect OpenProcess to lsass.exe
                    // with PROCESS_VM_READ | PROCESS_QUERY_INFORMATION
            },
        },
        HeuristicRule {
            id: "HEUR-005".into(),
            name: "Suspicious Temp File Execution".into(),
            severity: Severity::High,
            mitre_techniques: vec!["T1204.002".into()],
            evaluator: |event, _fields| {
                event.action == "create"
                    && event.category == EventCategory::Process
                    // Real implementation: check if exe_path is in temp directories
            },
        },
    ]
}

// ─── Submodules ─────────────────────────────────────────────────

pub mod engine;
pub mod rules;
pub mod alert_manager;
